/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedCartoesRouteImport } from './routes/_authenticated/cartoes'
import { Route as AuthenticatedCasaRouteImport } from './routes/_authenticated/casa'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedContasRouteImport } from './routes/_authenticated/contas'
import { Route as AuthenticatedDespesasRouteImport } from './routes/_authenticated/despesas'
import { Route as AuthenticatedFinanciamentosRouteImport } from './routes/_authenticated/financiamentos'
import { Route as AuthenticatedFluxoRouteImport } from './routes/_authenticated/fluxo'
import { Route as AuthenticatedInvestimentosRouteImport } from './routes/_authenticated/investimentos'
import { Route as AuthenticatedMercadoPagoRouteImport } from './routes/_authenticated/mercado-pago'
import { Route as AuthenticatedMetasRouteImport } from './routes/_authenticated/metas'
import { Route as AuthenticatedMotoRouteImport } from './routes/_authenticated/moto'
import { Route as AuthenticatedPatrimonioRouteImport } from './routes/_authenticated/patrimonio'
import { Route as AuthenticatedReceitasRouteImport } from './routes/_authenticated/receitas'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedViagensRouteImport } from './routes/_authenticated/viagens'
import { Route as AuthenticatedFaturasCardIdInvoiceKeyRouteImport } from './routes/_authenticated/faturas.$cardId.$invoiceKey'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCartoesRoute = AuthenticatedCartoesRouteImport.update({
  id: '/cartoes',
  path: '/cartoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCasaRoute = AuthenticatedCasaRouteImport.update({
  id: '/casa',
  path: '/casa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContasRoute = AuthenticatedContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDespesasRoute = AuthenticatedDespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanciamentosRoute =
  AuthenticatedFinanciamentosRouteImport.update({
    id: '/financiamentos',
    path: '/financiamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFluxoRoute = AuthenticatedFluxoRouteImport.update({
  id: '/fluxo',
  path: '/fluxo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvestimentosRoute =
  AuthenticatedInvestimentosRouteImport.update({
    id: '/investimentos',
    path: '/investimentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMercadoPagoRoute =
  AuthenticatedMercadoPagoRouteImport.update({
    id: '/mercado-pago',
    path: '/mercado-pago',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMetasRoute = AuthenticatedMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMotoRoute = AuthenticatedMotoRouteImport.update({
  id: '/moto',
  path: '/moto',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatrimonioRoute = AuthenticatedPatrimonioRouteImport.update({
  id: '/patrimonio',
  path: '/patrimonio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReceitasRoute = AuthenticatedReceitasRouteImport.update({
  id: '/receitas',
  path: '/receitas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedViagensRoute = AuthenticatedViagensRouteImport.update({
  id: '/viagens',
  path: '/viagens',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFaturasCardIdInvoiceKeyRoute =
  AuthenticatedFaturasCardIdInvoiceKeyRouteImport.update({
    id: '/faturas/$cardId/$invoiceKey',
    path: '/faturas/$cardId/$invoiceKey',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/cartoes': typeof AuthenticatedCartoesRoute
  '/casa': typeof AuthenticatedCasaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contas': typeof AuthenticatedContasRoute
  '/despesas': typeof AuthenticatedDespesasRoute
  '/financiamentos': typeof AuthenticatedFinanciamentosRoute
  '/fluxo': typeof AuthenticatedFluxoRoute
  '/investimentos': typeof AuthenticatedInvestimentosRoute
  '/mercado-pago': typeof AuthenticatedMercadoPagoRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/moto': typeof AuthenticatedMotoRoute
  '/patrimonio': typeof AuthenticatedPatrimonioRoute
  '/receitas': typeof AuthenticatedReceitasRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/viagens': typeof AuthenticatedViagensRoute
  '/faturas/$cardId/$invoiceKey': typeof AuthenticatedFaturasCardIdInvoiceKeyRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/cartoes': typeof AuthenticatedCartoesRoute
  '/casa': typeof AuthenticatedCasaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contas': typeof AuthenticatedContasRoute
  '/despesas': typeof AuthenticatedDespesasRoute
  '/financiamentos': typeof AuthenticatedFinanciamentosRoute
  '/fluxo': typeof AuthenticatedFluxoRoute
  '/investimentos': typeof AuthenticatedInvestimentosRoute
  '/mercado-pago': typeof AuthenticatedMercadoPagoRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/moto': typeof AuthenticatedMotoRoute
  '/patrimonio': typeof AuthenticatedPatrimonioRoute
  '/receitas': typeof AuthenticatedReceitasRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/viagens': typeof AuthenticatedViagensRoute
  '/': typeof AuthenticatedIndexRoute
  '/faturas/$cardId/$invoiceKey': typeof AuthenticatedFaturasCardIdInvoiceKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/cartoes': typeof AuthenticatedCartoesRoute
  '/_authenticated/casa': typeof AuthenticatedCasaRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/contas': typeof AuthenticatedContasRoute
  '/_authenticated/despesas': typeof AuthenticatedDespesasRoute
  '/_authenticated/financiamentos': typeof AuthenticatedFinanciamentosRoute
  '/_authenticated/fluxo': typeof AuthenticatedFluxoRoute
  '/_authenticated/investimentos': typeof AuthenticatedInvestimentosRoute
  '/_authenticated/mercado-pago': typeof AuthenticatedMercadoPagoRoute
  '/_authenticated/metas': typeof AuthenticatedMetasRoute
  '/_authenticated/moto': typeof AuthenticatedMotoRoute
  '/_authenticated/patrimonio': typeof AuthenticatedPatrimonioRoute
  '/_authenticated/receitas': typeof AuthenticatedReceitasRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/viagens': typeof AuthenticatedViagensRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/faturas/$cardId/$invoiceKey': typeof AuthenticatedFaturasCardIdInvoiceKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cartoes'
    | '/casa'
    | '/configuracoes'
    | '/contas'
    | '/despesas'
    | '/financiamentos'
    | '/fluxo'
    | '/investimentos'
    | '/mercado-pago'
    | '/metas'
    | '/moto'
    | '/patrimonio'
    | '/receitas'
    | '/relatorios'
    | '/viagens'
    | '/faturas/$cardId/$invoiceKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/cartoes'
    | '/casa'
    | '/configuracoes'
    | '/contas'
    | '/despesas'
    | '/financiamentos'
    | '/fluxo'
    | '/investimentos'
    | '/mercado-pago'
    | '/metas'
    | '/moto'
    | '/patrimonio'
    | '/receitas'
    | '/relatorios'
    | '/viagens'
    | '/'
    | '/faturas/$cardId/$invoiceKey'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/cartoes'
    | '/_authenticated/casa'
    | '/_authenticated/configuracoes'
    | '/_authenticated/contas'
    | '/_authenticated/despesas'
    | '/_authenticated/financiamentos'
    | '/_authenticated/fluxo'
    | '/_authenticated/investimentos'
    | '/_authenticated/mercado-pago'
    | '/_authenticated/metas'
    | '/_authenticated/moto'
    | '/_authenticated/patrimonio'
    | '/_authenticated/receitas'
    | '/_authenticated/relatorios'
    | '/_authenticated/viagens'
    | '/_authenticated/'
    | '/_authenticated/faturas/$cardId/$invoiceKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cartoes': {
      id: '/_authenticated/cartoes'
      path: '/cartoes'
      fullPath: '/cartoes'
      preLoaderRoute: typeof AuthenticatedCartoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/casa': {
      id: '/_authenticated/casa'
      path: '/casa'
      fullPath: '/casa'
      preLoaderRoute: typeof AuthenticatedCasaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contas': {
      id: '/_authenticated/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof AuthenticatedContasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/despesas': {
      id: '/_authenticated/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof AuthenticatedDespesasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financiamentos': {
      id: '/_authenticated/financiamentos'
      path: '/financiamentos'
      fullPath: '/financiamentos'
      preLoaderRoute: typeof AuthenticatedFinanciamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fluxo': {
      id: '/_authenticated/fluxo'
      path: '/fluxo'
      fullPath: '/fluxo'
      preLoaderRoute: typeof AuthenticatedFluxoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investimentos': {
      id: '/_authenticated/investimentos'
      path: '/investimentos'
      fullPath: '/investimentos'
      preLoaderRoute: typeof AuthenticatedInvestimentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mercado-pago': {
      id: '/_authenticated/mercado-pago'
      path: '/mercado-pago'
      fullPath: '/mercado-pago'
      preLoaderRoute: typeof AuthenticatedMercadoPagoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metas': {
      id: '/_authenticated/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AuthenticatedMetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/moto': {
      id: '/_authenticated/moto'
      path: '/moto'
      fullPath: '/moto'
      preLoaderRoute: typeof AuthenticatedMotoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patrimonio': {
      id: '/_authenticated/patrimonio'
      path: '/patrimonio'
      fullPath: '/patrimonio'
      preLoaderRoute: typeof AuthenticatedPatrimonioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/receitas': {
      id: '/_authenticated/receitas'
      path: '/receitas'
      fullPath: '/receitas'
      preLoaderRoute: typeof AuthenticatedReceitasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/viagens': {
      id: '/_authenticated/viagens'
      path: '/viagens'
      fullPath: '/viagens'
      preLoaderRoute: typeof AuthenticatedViagensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/faturas/$cardId/$invoiceKey': {
      id: '/_authenticated/faturas/$cardId/$invoiceKey'
      path: '/faturas/$cardId/$invoiceKey'
      fullPath: '/faturas/$cardId/$invoiceKey'
      preLoaderRoute: typeof AuthenticatedFaturasCardIdInvoiceKeyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCartoesRoute: typeof AuthenticatedCartoesRoute
  AuthenticatedCasaRoute: typeof AuthenticatedCasaRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedContasRoute: typeof AuthenticatedContasRoute
  AuthenticatedDespesasRoute: typeof AuthenticatedDespesasRoute
  AuthenticatedFinanciamentosRoute: typeof AuthenticatedFinanciamentosRoute
  AuthenticatedFluxoRoute: typeof AuthenticatedFluxoRoute
  AuthenticatedInvestimentosRoute: typeof AuthenticatedInvestimentosRoute
  AuthenticatedMercadoPagoRoute: typeof AuthenticatedMercadoPagoRoute
  AuthenticatedMetasRoute: typeof AuthenticatedMetasRoute
  AuthenticatedMotoRoute: typeof AuthenticatedMotoRoute
  AuthenticatedPatrimonioRoute: typeof AuthenticatedPatrimonioRoute
  AuthenticatedReceitasRoute: typeof AuthenticatedReceitasRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedViagensRoute: typeof AuthenticatedViagensRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedFaturasCardIdInvoiceKeyRoute: typeof AuthenticatedFaturasCardIdInvoiceKeyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCartoesRoute: AuthenticatedCartoesRoute,
  AuthenticatedCasaRoute: AuthenticatedCasaRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedContasRoute: AuthenticatedContasRoute,
  AuthenticatedDespesasRoute: AuthenticatedDespesasRoute,
  AuthenticatedFinanciamentosRoute: AuthenticatedFinanciamentosRoute,
  AuthenticatedFluxoRoute: AuthenticatedFluxoRoute,
  AuthenticatedInvestimentosRoute: AuthenticatedInvestimentosRoute,
  AuthenticatedMercadoPagoRoute: AuthenticatedMercadoPagoRoute,
  AuthenticatedMetasRoute: AuthenticatedMetasRoute,
  AuthenticatedMotoRoute: AuthenticatedMotoRoute,
  AuthenticatedPatrimonioRoute: AuthenticatedPatrimonioRoute,
  AuthenticatedReceitasRoute: AuthenticatedReceitasRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedViagensRoute: AuthenticatedViagensRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedFaturasCardIdInvoiceKeyRoute:
    AuthenticatedFaturasCardIdInvoiceKeyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
