/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReceitasRouteImport } from './routes/receitas'
import { Route as PatrimonioRouteImport } from './routes/patrimonio'
import { Route as MercadoPagoRouteImport } from './routes/mercado-pago'
import { Route as InvestimentosRouteImport } from './routes/investimentos'
import { Route as FluxoRouteImport } from './routes/fluxo'
import { Route as FinanciamentosRouteImport } from './routes/financiamentos'
import { Route as DespesasRouteImport } from './routes/despesas'
import { Route as ContasRouteImport } from './routes/contas'
import { Route as CartoesRouteImport } from './routes/cartoes'
import { Route as IndexRouteImport } from './routes/index'

const ReceitasRoute = ReceitasRouteImport.update({
  id: '/receitas',
  path: '/receitas',
  getParentRoute: () => rootRouteImport,
} as any)
const PatrimonioRoute = PatrimonioRouteImport.update({
  id: '/patrimonio',
  path: '/patrimonio',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadoPagoRoute = MercadoPagoRouteImport.update({
  id: '/mercado-pago',
  path: '/mercado-pago',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestimentosRoute = InvestimentosRouteImport.update({
  id: '/investimentos',
  path: '/investimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const FluxoRoute = FluxoRouteImport.update({
  id: '/fluxo',
  path: '/fluxo',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanciamentosRoute = FinanciamentosRouteImport.update({
  id: '/financiamentos',
  path: '/financiamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const DespesasRoute = DespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => rootRouteImport,
} as any)
const ContasRoute = ContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => rootRouteImport,
} as any)
const CartoesRoute = CartoesRouteImport.update({
  id: '/cartoes',
  path: '/cartoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cartoes': typeof CartoesRoute
  '/contas': typeof ContasRoute
  '/despesas': typeof DespesasRoute
  '/financiamentos': typeof FinanciamentosRoute
  '/fluxo': typeof FluxoRoute
  '/investimentos': typeof InvestimentosRoute
  '/mercado-pago': typeof MercadoPagoRoute
  '/patrimonio': typeof PatrimonioRoute
  '/receitas': typeof ReceitasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cartoes': typeof CartoesRoute
  '/contas': typeof ContasRoute
  '/despesas': typeof DespesasRoute
  '/financiamentos': typeof FinanciamentosRoute
  '/fluxo': typeof FluxoRoute
  '/investimentos': typeof InvestimentosRoute
  '/mercado-pago': typeof MercadoPagoRoute
  '/patrimonio': typeof PatrimonioRoute
  '/receitas': typeof ReceitasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cartoes': typeof CartoesRoute
  '/contas': typeof ContasRoute
  '/despesas': typeof DespesasRoute
  '/financiamentos': typeof FinanciamentosRoute
  '/fluxo': typeof FluxoRoute
  '/investimentos': typeof InvestimentosRoute
  '/mercado-pago': typeof MercadoPagoRoute
  '/patrimonio': typeof PatrimonioRoute
  '/receitas': typeof ReceitasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cartoes'
    | '/contas'
    | '/despesas'
    | '/financiamentos'
    | '/fluxo'
    | '/investimentos'
    | '/mercado-pago'
    | '/patrimonio'
    | '/receitas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cartoes'
    | '/contas'
    | '/despesas'
    | '/financiamentos'
    | '/fluxo'
    | '/investimentos'
    | '/mercado-pago'
    | '/patrimonio'
    | '/receitas'
  id:
    | '__root__'
    | '/'
    | '/cartoes'
    | '/contas'
    | '/despesas'
    | '/financiamentos'
    | '/fluxo'
    | '/investimentos'
    | '/mercado-pago'
    | '/patrimonio'
    | '/receitas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartoesRoute: typeof CartoesRoute
  ContasRoute: typeof ContasRoute
  DespesasRoute: typeof DespesasRoute
  FinanciamentosRoute: typeof FinanciamentosRoute
  FluxoRoute: typeof FluxoRoute
  InvestimentosRoute: typeof InvestimentosRoute
  MercadoPagoRoute: typeof MercadoPagoRoute
  PatrimonioRoute: typeof PatrimonioRoute
  ReceitasRoute: typeof ReceitasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/receitas': {
      id: '/receitas'
      path: '/receitas'
      fullPath: '/receitas'
      preLoaderRoute: typeof ReceitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrimonio': {
      id: '/patrimonio'
      path: '/patrimonio'
      fullPath: '/patrimonio'
      preLoaderRoute: typeof PatrimonioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercado-pago': {
      id: '/mercado-pago'
      path: '/mercado-pago'
      fullPath: '/mercado-pago'
      preLoaderRoute: typeof MercadoPagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investimentos': {
      id: '/investimentos'
      path: '/investimentos'
      fullPath: '/investimentos'
      preLoaderRoute: typeof InvestimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fluxo': {
      id: '/fluxo'
      path: '/fluxo'
      fullPath: '/fluxo'
      preLoaderRoute: typeof FluxoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financiamentos': {
      id: '/financiamentos'
      path: '/financiamentos'
      fullPath: '/financiamentos'
      preLoaderRoute: typeof FinanciamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despesas': {
      id: '/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof DespesasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contas': {
      id: '/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof ContasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartoes': {
      id: '/cartoes'
      path: '/cartoes'
      fullPath: '/cartoes'
      preLoaderRoute: typeof CartoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartoesRoute: CartoesRoute,
  ContasRoute: ContasRoute,
  DespesasRoute: DespesasRoute,
  FinanciamentosRoute: FinanciamentosRoute,
  FluxoRoute: FluxoRoute,
  InvestimentosRoute: InvestimentosRoute,
  MercadoPagoRoute: MercadoPagoRoute,
  PatrimonioRoute: PatrimonioRoute,
  ReceitasRoute: ReceitasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
